services:
  - type: web
    name: biblioteca-web
    env: dotnet
    plan: free
    buildCommand: dotnet publish -c Release -o publish
    startCommand: cd publish && dotnet BibliotecaWeb.dll
    disk:
      name: datos
      mountPath: /opt/render/project/src
      sizeGB: 1